
INSERT INTO CURRENCY(CURRENCY_ID,CURRENCY_CODE) VALUES (1,'AUD');

INSERT INTO CURRENCY(CURRENCY_ID,CURRENCY_CODE) VALUES (2,'SGD');


INSERT INTO ACCOUNT_TYPE(ACCOUNT_TYPE_ID, ACCOUNT_TYPE) VALUES (1,'SAVINGS');

INSERT INTO ACCOUNT_TYPE(ACCOUNT_TYPE_ID, ACCOUNT_TYPE) VALUES (2,'CURRENT');

INSERT INTO Account (ACCOUNT_ID,Account_balance, Account_Name ,Balance_date ,Account_type_id ,currency_id )VALUES (1000,30000.00,'TestAccount1',TO_DATE('02/01/2019', 'DD/MM/YYYY'),1,1);



INSERT INTO Account (ACCOUNT_ID,Account_balance, Account_Name ,Balance_date ,Account_type_id ,currency_id )VALUES (1001,10000.00,'TestAccount1Cur',TO_DATE('15/02/2019', 'DD/MM/YYYY'),2,1);



INSERT INTO CUSTOMER(CUSTOMER_ID,CUSTOMER_NAME) VALUES (100,'CUST1');

INSERT INTO CUSTOMER(CUSTOMER_ID,CUSTOMER_NAME) VALUES (101,'CUST2');

INSERT INTO CUSTOMER_ACCOUNT(CUSTOMER_ID,ACCOUNT_ID) VALUES (100,1000);
INSERT INTO CUSTOMER_ACCOUNT(CUSTOMER_ID,ACCOUNT_ID) VALUES (100,1001);



INSERT INTO TRANSACTION(TRANSACTION_ID,ACCOUNT_ID, TRANSACTION_DATE, TRANSACTION_TYPE,CURRENCY_ID,CREDIT_AMOUNT) VALUES(11,1000,TO_DATE('12/11/2018', 'DD/MM/YYYY'),'CREDIT',1, 8000.00);

INSERT INTO TRANSACTION(TRANSACTION_ID,ACCOUNT_ID, TRANSACTION_DATE, TRANSACTION_TYPE,CURRENCY_ID,DEBIT_AMOUNT) VALUES(10,1000,TO_DATE('01/02/2018', 'DD/MM/YYYY'),'DEBIT',1, 40.00);
